### ISSUE TITLE
Dimensions of Output Tree / Matrix

### ISSUE THREAD

**Issue by gordonkoehn** [PASSIONLab/HUNTRESS#1]
Hi HUNTRESS Developers

I'd like to verify my understanding of the output of HUNTRESS with you. 

**Are the number of mutations/non-root nodes of the tree proposed by HUNTRESS equal to the number of mutations in the inputted mutation matrix ?**

Or is it possible, however unlikely, that given high error rates and a small number of cells a mutation may not be considered part of the history by HUNTRESS, i.e. number of mutations in the mutation matrix is larger than the number of mutations in the tree?

I am asking because I may have encountered such a case - trying to add a reproducible example as soon as I recover it !

Thank you in advance!  - Best Regards from Comp. Bio. ETH Zürich 

Gordon

**Comment by cankizilkale** [comment]
If what you are asking is whether the number of ones in the input matrix is equal to the number of ones in the output matrix then it doesn't have to be. Likewise given high error rates and the presence of large number of missing elements it should be possible to have a row with only zeros in the output matrix.

Feel free to dm me for follow up questions. 

Best, 

Can

**Comment by gordonkoehn** [comment]
Perfect -  yes, that was indeed my question. Thank you for verifying!
